<a href="https://colab.research.google.com/github/jonaidsharif/Numpy-in-Python-A-to-Z-in-Bangla/blob/main/Numpy_Tutorial_Step_by_Step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load Numpy(pip install)

In [ ]:
import numpy as np

The Basic

In [ ]:
first = np.array([1,2,3])
print(first)

[1 2 3]


In [ ]:
second = np.array([[1,2,3,5,7,9],[4,5,6,3,7,9]])
print(second)

[[1 2 3 5 7 9]
 [4 5 6 3 7 9]]


In [ ]:
#Get direction

first.ndim

1

In [ ]:
#Get direction

second.ndim

2

In [ ]:
#Get shape

second.shape

(2, 6)

In [ ]:
#Get type

first.dtype

dtype('int64')

In [ ]:
first = np.array([1,2,3], dtype='int16')
print(first)

[1 2 3]


In [ ]:
#Get type

first.dtype

dtype('int16')

In [ ]:
#Get size

first.itemsize

2

In [ ]:
first = np.array([1,2,3], dtype='int32')
print(first)

[1 2 3]


In [ ]:
#Get size

first.itemsize

4

In [ ]:
#Get size

first.itemsize
second.itemsize

8

In [ ]:
#Get total size

first.nbytes

12

Acessing/Changing specific elements, rows, columns etc

In [ ]:
first = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(first)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element(r, c)

first[1,5]

13

In [ ]:
#Get a specific element(r, c)

first[1,-2]

13

In [ ]:
#Get a specific element(r, c)

first[1,-5]

10

In [ ]:
#Get a specific row

first[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column

first[:, 2]

array([ 3, 10])

In [ ]:
#Get a specific column

first[:, 5]

array([ 6, 13])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

first[0, 1:6:1]

array([2, 3, 4, 5, 6])

In [ ]:
#  Getting a little more fancy [startindex:endindex:stepsize]
first[0, 1:6:2]

array([2, 4, 6])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

first[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

first[0, 1:6:-2]

array([], dtype=int64)

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

first[0, 1:-2:2]

array([2, 4])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]

first[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
# replace value to the first variable
first[1,5] = 30
print(first)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 30 14]]


In [ ]:
#replace value and also changing range of the value
first[1,6] = 20
print(first)

first[:, 3] = [1,2]
print(first)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 30 20]]
[[ 1  2  3  1  5  6  7]
 [ 8  9 10  2 12 30 20]]


In [ ]:
#replace value and also changing range of the value
first[1,4] = 15
print(first)

first[:, 4] = [1,2]
print(first)

[[ 1  2  3  1  5  6  7]
 [ 8  9 10  2 15 30 20]]
[[ 1  2  3  1  1  6  7]
 [ 8  9 10  2  2 30 20]]


3D Examples

In [ ]:
second = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(second)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element(work outside in)

second[0,1,1]

4

In [ ]:
#Get specific element the replace

second[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
#Get specific element the replace

second[:,1,:] = [[9,9],[8,8]]
print(second)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
#Get specific element the replace

second[:,1,:] = [[9,9,9],[8,8]]
print(second)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Initializing different type of arrays

In [ ]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#All other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
#All other number
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [ ]:
#All other number (full_like)
np.full_like(first.shape, 4)

array([4, 4])

In [ ]:
#All other number (full_like)
np.full_like(first, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random decimals numbers
np.random.rand(4,2)

array([[0.1703471 , 0.76115897],
       [0.16789921, 0.42492592],
       [0.8382951 , 0.77255179],
       [0.730086  , 0.20850912]])

In [ ]:
#Random decimals numbers
np.random.rand(4,4,2)

array([[[0.08859003, 0.66377219],
        [0.51754363, 0.39340435],
        [0.00670321, 0.62917929],
        [0.26386706, 0.89404795]],

       [[0.74963928, 0.29307167],
        [0.10667356, 0.14552849],
        [0.92354793, 0.51320139],
        [0.80094009, 0.19521629]],

       [[0.50332561, 0.88104018],
        [0.91942647, 0.59247591],
        [0.89538976, 0.83947102],
        [0.42005545, 0.42904239]],

       [[0.55453996, 0.07556306],
        [0.56907802, 0.29708935],
        [0.31435333, 0.84737748],
        [0.36070536, 0.93372004]]])

In [ ]:
#Random decimals numbers
np.random.random_sample(first.shape)

array([[0.49955241, 0.8936016 , 0.95952275, 0.82927143, 0.90433119,
        0.38969236, 0.5728202 ],
       [0.31021581, 0.08470214, 0.34674929, 0.83299848, 0.95344924,
        0.63912107, 0.30862105]])

In [ ]:
#Random integer values
np.random.randint(6)

5

In [ ]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[1, 6, 1],
       [5, 6, 4],
       [6, 0, 6]])

In [ ]:
#Random integer values
np.random.randint(4,7, size=(3,3))

array([[5, 6, 6],
       [5, 4, 5],
       [6, 5, 6]])

In [ ]:
#Random integer values
np.random.randint(-4,7, size=(3,3))

array([[ 1, -4, -4],
       [-2, -1,  4],
       [ 3,  2,  0]])

In [ ]:
#The identify matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
ra1 = np.repeat(arr,3, axis=1)
print(ra1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
ra1 = np.repeat(arr,3, axis=0)
print(ra1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be carefully when copying array!!!

In [ ]:
first = np.array([1,2,3])
second = first
second[0] = 100
print(first)

[100   2   3]


In [ ]:
first = np.array([1,2,3])
second = first.copy() # Call the copy method to create a copy
second[0] = 100
print(first)

[1 2 3]


Mathematics

In [ ]:
first = np.array([1,2,3,4])
print(first)

[1 2 3 4]


In [ ]:
first + 2

array([3, 4, 5, 6])

In [ ]:
first - 2

array([-1,  0,  1,  2])

In [ ]:
first * 2

array([2, 4, 6, 8])

In [ ]:
first / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
second = np.array([1,0,1,0])
first + second

array([2, 2, 4, 4])

In [ ]:
first ** 2

array([ 1,  4,  9, 16])

In [ ]:
#Take the sin
np.cos(first)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [ ]:
first = np.ones((2,3))
print(first)

second = np.full((3,2), 2)
print(second)

np.matmul(first,second)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#Find the determinant
thrid = np.identity(2)
np.linalg.det(thrid)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats)

21

In [100]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [102]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [103]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [105]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [104]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [106]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [107]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [109]:
#Vertically stacking vectors
vecti1 = np.array([1,2,3,4])
vecti2 = np.array([5,6,7,8])

np.vstack([vecti1, vecti2, vecti1, vecti2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
#Horizontal stack
hori1 = np.ones((2,4))
hori2 = np.zeros((2,2))

np.hstack((hori1, hori2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

Load Data from File

Boolean Masking and Advanced indexing